#dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
#  - "pypy3" lets not do pypy right now

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run black . --check
  - poetry run mypy runrestic --ignore-missing-imports
  - poetry run pytest
